use strict;
use warnings;
use Test::More 0.88;
# This is a relatively nice way to avoid Test::NoWarnings breaking our
# expectations by adding extra tests, without using no_plan.  It also helps
# avoid any other test module that feels introducing random tests, or even
# test plans, is a nice idea.
our $success = 0;
END { $success && done_testing; }

# List our own version used to generate this
my $v = "\nGenerated by Dist::Zilla::Plugin::ReportVersions::Tiny v1.10\n";

eval {                     # no excuses!
    # report our Perl details
    my $want = '5.012';
    $v .= "perl: $] (wanted $want) on $^O from $^X\n\n";
};
defined($@) and diag("$@");

# Now, our module version dependencies:
sub pmver {
    my ($module, $wanted) = @_;
    $wanted = " (want $wanted)";
    my $pmver;
    eval "require $module;";
    if ($@) {
        if ($@ =~ m/Can't locate .* in \@INC/) {
            $pmver = 'module not found.';
        } else {
            diag("${module}: $@");
            $pmver = 'died during require.';
        }
    } else {
        my $version;
        eval { $version = $module->VERSION; };
        if ($@) {
            diag("${module}: $@");
            $pmver = 'died during VERSION check.';
        } elsif (defined $version) {
            $pmver = "$version";
        } else {
            $pmver = '<undef>';
        }
    }

    # So, we should be good, right?
    return sprintf('%-45s => %-10s%-15s%s', $module, $pmver, $wanted, "\n");
}

eval { $v .= pmver('App::Cmd::Setup','0.309') };
eval { $v .= pmver('Carp','any version') };
eval { $v .= pmver('Class::Load','any version') };
eval { $v .= pmver('Clone','any version') };
eval { $v .= pmver('Data::Dump','any version') };
eval { $v .= pmver('Digest::MD5','any version') };
eval { $v .= pmver('Exporter','any version') };
eval { $v .= pmver('File::Temp','any version') };
eval { $v .= pmver('IPC::System::Simple','any version') };
eval { $v .= pmver('List::Util','any version') };
eval { $v .= pmver('Log::Any','any version') };
eval { $v .= pmver('Log::Any::Adapter','any version') };
eval { $v .= pmver('Module::Build','0.3601') };
eval { $v .= pmver('Module::Pluggable','any version') };
eval { $v .= pmver('Moo','any version') };
eval { $v .= pmver('Moo::Role','any version') };
eval { $v .= pmver('MooX::Types::MooseLike::Base','any version') };
eval { $v .= pmver('Package::Stash','any version') };
eval { $v .= pmver('Path::Class','any version') };
eval { $v .= pmver('Safe::Isa','any version') };
eval { $v .= pmver('Sereal::Decoder','any version') };
eval { $v .= pmver('Sereal::Encoder','any version') };
eval { $v .= pmver('Test::Compile','any version') };
eval { $v .= pmver('Test::Modern','any version') };
eval { $v .= pmver('Test::More','0.88') };
eval { $v .= pmver('Try::Tiny','any version') };
eval { $v .= pmver('YAML::XS','0.35') };
eval { $v .= pmver('autodie','any version') };
eval { $v .= pmver('namespace::clean','any version') };
eval { $v .= pmver('parent','any version') };
eval { $v .= pmver('strict','any version') };
eval { $v .= pmver('warnings','any version') };


# All done.
$v .= <<'EOT';

Thanks for using my code.  I hope it works for you.
If not, please try and include this output in the bug report.
That will help me reproduce the issue and solve your problem.

EOT

diag($v);
ok(1, "we really didn't test anything, just reporting data");
$success = 1;

# Work around another nasty module on CPAN. :/
no warnings 'once';
$Template::Test::NO_FLUSH = 1;
exit 0;
